sudo: required

services:
  - docker

env:
  - DOCKER_IMAGE_NAME=gazoapp/phinx

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME
